### ISSUE TITLE
Image Document correction feature

### ISSUE THREAD

**Issue by msampathkumar** [Imaginea/vitaFlow#21]
For some extent, images with quality can be improved.

* Skewed
* rotated.
* cropped to the requirement.

For reading images and writing images to files, please use matplotlib.pytplot.(imread/imsave)

__Resources:__
* https://mzucker.github.io/2016/10/11/unprojecting-text-with-ellipses.html
* https://www.cs.toronto.edu/~guerzhoy/oriviz/crv17.pdf

Refer to https://github.com/Imaginea/vitaFlow/issues/32

**Comment by msampathkumar** [comment]
A sample notebook is added to git repo but requires testing and packing to a python module to be quickly usable.

[https://github.com/Imaginea/vitaFlow/tree/annotate_server/vitaflow/annotate_server/notebooks](https://github.com/Imaginea/vitaFlow/tree/annotate_server/vitaflow/annotate_server/notebooks)

**Comment by thak123** [comment]
This works for images with dark backgrounds...
try it with light background like white...
the edge detection algo fails miserably thereby failing to complete the remaining steps in pipeline

**Comment by Mageswaran1989** [comment]
@msampathkumar update plz...
