### ISSUE TITLE
See the feasibility to add Brat (http://brat.nlplab.org/examples.html) as part of the current data flow.

### ISSUE THREAD

**Issue by Mageswaran1989** [Imaginea/vitaFlow#4]

**Comment by Mageswaran1989** [comment]
@reddyanilkumar this may be required...see the feasibility

**Comment by msampathkumar** [comment]
Sharing initial introspection of Brat. 

Brat seems to be written using native python CGI packages and so integrating this into Annotation would required many man hours.

_One easy & quick work-around is running two server, and setting a pipeline that easy transitions to Brat page and lands us back into Annotation Server_

In terms of scaling aspects as well, this quick-around would be really useful in many ways.
