### ISSUE TITLE
Fix directory separator in the path.

### ISSUE THREAD

**Issue by thak123** [Imaginea/vitaFlow#6]
We see a // in the path that are provided. It means somewhere / is hardcoded. It means the code can break on windows system

Found previous version at /home/gaurishk/vitaFlow//conll_2003_dataset/preprocessed_data//train/
Preprocessing the test data...
Found previous version at /home/gaurishk/vitaFlow//conll_2003_dataset/preprocessed_data//test/
Preprocessing the validation data...
Found previous version at /home/gaurishk/vitaFlow//conll_2003_dataset/preprocessed_data//val/
Preparing the vocab for the text col: 0

**Comment by msampathkumar** [comment]
WIP

**Comment by msampathkumar** [comment]
This is completed I believe. Let close this for now.
